paginates_per: 12
name_max: 50
email_max: 255
pass_min: 6
per_page: 10
avatar: 50
expire_time: 2
product_promotion: 3
product_shoe: 3
product_new: 6
accept: "image/jpeg,image/gif,image/png, image/jpg"
greater_than: 0
phone_min: 10
phone_max: 13
